name: Build

on:
  push:
    branches: [ sqlite3mc ]
  pull_request:
    branches: [ sqlite3mc ]

jobs:
  build:
    uses: ./.github/workflows/build-reusable.yml
    secrets:
      MUSL_CC_BIN: ${{ secrets.MUSL_CC_BIN }}
